<?php
namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Models\Vehicle;
use Illuminate\Support\Facades\Log;
use Illuminate\Http\Request;

class AdminVehicleController extends Controller
{
    public function index()
    {
        $vehicles = Vehicle::all();
        return view('admin.crud.vehicles.index', compact('vehicles'));
    }

    public function add()
    {
        return view('admin.crud.vehicles.add');
    }

    public function store(Request $request)
    {
        try {
            $request->validate([
                'name' => 'required|string|max:500',
                'model' => 'required|string|max:500',
                'phone' => 'required|string|max:500',
                'car_image' => 'required|image|mimes:jpeg,png,jpg,gif,svg|max:2048',
            ]);

            $validatedData = $request->only(['name', 'model', 'phone']);

            // Handle image upload
            if ($request->hasFile('car_image')) {
                $image = $request->file('car_image');
                $imageName = time() . '_' . $image->getClientOriginalName();
                $image->move(public_path('uploads/vehicles'), $imageName);
                $validatedData['car_image'] = 'uploads/vehicles/' . $imageName;
            }

            Log::info('Validated Vehicle data:', $validatedData);

            // Slug will be auto-generated by the model
            $vehicle = Vehicle::create([
                'name' => $validatedData['name'],
                'model' => $validatedData['model'],
                'phone' => $validatedData['phone'],
                'car_image' => $validatedData['car_image'] ?? null,
            ]);

            Log::info('Vehicle created successfully:', ['id' => $vehicle->id, 'slug' => $vehicle->slug ?? 'N/A']);

            return redirect()->route('admin.vehicle.index')->with('success', 'Vehicle added successfully.');
        } catch (\Exception $e) {
            Log::error('Error while creating Vehicle:', ['message' => $e->getMessage()]);
            return redirect()->back()->withErrors($e->getMessage())->withInput();
        }
    }

    public function edit($id)
    {
        $vehicle = Vehicle::findOrFail($id);
        return view('admin.crud.vehicles.edit', compact('vehicle'));
    }

    public function update(Request $request, $id)
    {
        try {
            $request->validate([
                'name' => 'required|string|max:500',
                'model' => 'required|string|max:500',
                'phone' => 'required|string|max:500',
                'car_image' => 'nullable|image|mimes:jpeg,png,jpg,gif,svg|max:2048',
            ]);

            $vehicle = Vehicle::findOrFail($id);
            
            // Check if name has changed to regenerate slug
            $nameChanged = $vehicle->name !== $request->name;
            
            $updateData = [
                'name' => $request->name,
                'model' => $request->model,
                'phone' => $request->phone,
            ];

            // If name changed, clear slug to trigger auto-generation
            if ($nameChanged) {
                $updateData['slug'] = null;
            }

            // Handle image upload
            if ($request->hasFile('car_image')) {
                // Delete old image if exists
                if ($vehicle->car_image && file_exists(public_path($vehicle->car_image))) {
                    unlink(public_path($vehicle->car_image));
                }
                
                $image = $request->file('car_image');
                $imageName = time() . '_' . $image->getClientOriginalName();
                $image->move(public_path('uploads/vehicles'), $imageName);
                $updateData['car_image'] = 'uploads/vehicles/' . $imageName;
            }

            $vehicle->update($updateData);

            Log::info('Vehicle updated successfully:', ['id' => $vehicle->id, 'slug' => $vehicle->fresh()->slug ?? 'N/A']);

            return redirect()->route('admin.vehicle.index')->with('success', 'Vehicle updated successfully.');
        } catch (\Exception $e) {
            Log::error('Vehicle update error:', ['message' => $e->getMessage()]);
            return redirect()->back()->withErrors($e->getMessage())->withInput();
        }
    }

    public function destroy($id)
    {
        try {
            $vehicle = Vehicle::findOrFail($id);
            
            // Delete associated files
            if ($vehicle->car_image && file_exists(public_path($vehicle->car_image))) {
                unlink(public_path($vehicle->car_image));
            }
            
            $vehicle->delete();
            return redirect()->route('admin.vehicle.index')->with('success', 'Vehicle deleted successfully.');
        } catch (\Exception $e) {
            Log::error('Vehicle delete error:', ['message' => $e->getMessage()]);
            return redirect()->back()->withErrors('Could not delete Vehicle.');
        }
    }
}
