<?php
namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Models\MiniService;
use Illuminate\Support\Facades\Log;
use Illuminate\Http\Request;

class AdminMiniServiceController extends Controller
{
    public function toggleVisibility(Request $request, $id)
    {
        try {
            $miniService = MiniService::findOrFail($id);
            // Toggle the visibility: if it's 1, make it 0; if it's 0, make it 1
            $miniService->visibility = $miniService->visibility ? 0 : 1;
            $miniService->save();
            
            return redirect()->route('admin.mini-service.index')->with('success', 'Mini Service visibility updated successfully.');
        } catch (\Exception $e) {
            Log::error('Mini Service visibility toggle error:', ['message' => $e->getMessage()]);
            return redirect()->back()->withErrors('Could not update Mini Service visibility.');
        }
    }

    public function index()
    {
        $miniServices = MiniService::all();
        return view('admin.crud.mini-services.index', compact('miniServices'));
    }

    public function add()
    {
        return view('admin.crud.mini-services.add');
    }

    public function store(Request $request)
    {
        try {
            $request->validate([
                'title' => 'required|string|max:255',
                'icon' => 'required|string|max:255',
                'image' => 'required|image|mimes:jpeg,png,jpg,gif,svg|max:2048',
                'visibility' => 'nullable|integer',
            ]);

            $validatedData = $request->only(['title', 'icon', 'visibility']);

            // Handle image upload
            if ($request->hasFile('image')) {
                $image = $request->file('image');
                $imageName = time() . '_' . $image->getClientOriginalName();
                $image->move(public_path('uploads/mini-services'), $imageName);
                $validatedData['image'] = 'uploads/mini-services/' . $imageName;
            }

            Log::info('Validated Mini Service data:', $validatedData);

            // Slug will be auto-generated by the model
            $miniService = MiniService::create([
                'title' => $validatedData['title'],
                'icon' => $validatedData['icon'],
                'image' => $validatedData['image'] ?? null,
                'visibility' => $validatedData['visibility'] ?? 1,
            ]);

         
            return redirect()->route('admin.mini-service.index')->with('success', 'Mini Service added successfully.');
        } catch (\Exception $e) {
            Log::error('Error while creating Mini Service:', ['message' => $e->getMessage()]);
            return redirect()->back()->withErrors($e->getMessage())->withInput();
        }
    }

    public function edit($id)
    {
        $miniService = MiniService::findOrFail($id);
        return view('admin.crud.mini-services.edit', compact('miniService'));
    }

    public function update(Request $request, $id)
    {
        try {
            $request->validate([
                'title' => 'required|string|max:255',
                'icon' => 'required|string|max:255',
                'image' => 'nullable|image|mimes:jpeg,png,jpg,gif,svg|max:2048',
                'visibility' => 'nullable|integer',
            ]);

            $miniService = MiniService::findOrFail($id);
            
            // Check if title has changed to regenerate slug
            $titleChanged = $miniService->title !== $request->title;
            
            $updateData = [
                'title' => $request->title,
                'icon' => $request->icon,
                'visibility' => $request->visibility ?? 1,
            ];

       
            // Handle image upload
            if ($request->hasFile('image')) {
                // Delete old image if exists
                if ($miniService->image && file_exists(public_path($miniService->image))) {
                    unlink(public_path($miniService->image));
                }
                
                $image = $request->file('image');
                $imageName = time() . '_' . $image->getClientOriginalName();
                $image->move(public_path('uploads/mini-services'), $imageName);
                $updateData['image'] = 'uploads/mini-services/' . $imageName;
            }

            $miniService->update($updateData);

       
            return redirect()->route('admin.mini-service.index')->with('success', 'Mini Service updated successfully.');
        } catch (\Exception $e) {
            Log::error('Mini Service update error:', ['message' => $e->getMessage()]);
            return redirect()->back()->withErrors($e->getMessage())->withInput();
        }
    }

    public function destroy($id)
    {
        try {
            $miniService = MiniService::findOrFail($id);
            
            // Delete associated files
            if ($miniService->image && file_exists(public_path($miniService->image))) {
                unlink(public_path($miniService->image));
            }
            
            $miniService->delete();
            return redirect()->route('admin.mini-service.index')->with('success', 'Mini Service deleted successfully.');
        } catch (\Exception $e) {
            Log::error('Mini Service delete error:', ['message' => $e->getMessage()]);
            return redirect()->back()->withErrors('Could not delete Mini Service.');
        }
    }
}
